upstream:
  externalResolvers:
    # Quad9
    - 9.9.9.9
    - 149.112.112.112
    # OpenDNS
    - 208.67.222.222
    - 208.67.220.220
    # AdGuard DNS
    - 94.140.14.140
    - 94.140.14.141
blocking:
  blackLists:
    malwares:
      - https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/phishing-domains-ACTIVE.txt
      - https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/master/hosts/hosts0
      - https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/master/hosts/hosts1
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/data/malwaredomainlist.com/hosts
      - https://mirror1.malwaredomains.com/files/justdomains
    trackers:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.2o7Net/hosts
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/data/yoyo.org/hosts
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    adds:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - http://sysctl.org/cameleon/hosts
  clientGroupsBlock:
    default:
      - malwares
      - trackers
      # - adds
  blockType: zeroIp
prometheus:
  enable: true
port: 53
httpPort: 4000